// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/calculator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message containing two operands
type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *OperationRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

// Response message containing the result
type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/calculator.proto\x12\n" +
	"calculator\".\n" +
	"\x10OperationRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"A\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa9\x02\n" +
	"\n" +
	"Calculator\x12B\n" +
	"\x03Add\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n" +
	"\bSubtract\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n" +
	"\bMultiply\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12E\n" +
	"\x06Divide\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponseB5Z3github.com/carlosealves2/test-auto-version/proto/pbb\x06proto3"

var (
	file_proto_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_proto_rawDescData []byte
)

func file_proto_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_proto_rawDescData
}

var file_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calculator_proto_goTypes = []any{
	(*OperationRequest)(nil),  // 0: calculator.OperationRequest
	(*OperationResponse)(nil), // 1: calculator.OperationResponse
}
var file_proto_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Add:input_type -> calculator.OperationRequest
	0, // 1: calculator.Calculator.Subtract:input_type -> calculator.OperationRequest
	0, // 2: calculator.Calculator.Multiply:input_type -> calculator.OperationRequest
	0, // 3: calculator.Calculator.Divide:input_type -> calculator.OperationRequest
	1, // 4: calculator.Calculator.Add:output_type -> calculator.OperationResponse
	1, // 5: calculator.Calculator.Subtract:output_type -> calculator.OperationResponse
	1, // 6: calculator.Calculator.Multiply:output_type -> calculator.OperationResponse
	1, // 7: calculator.Calculator.Divide:output_type -> calculator.OperationResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calculator_proto_init() }
func file_proto_calculator_proto_init() {
	if File_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_proto = out.File
	file_proto_calculator_proto_goTypes = nil
	file_proto_calculator_proto_depIdxs = nil
}
