name: Release

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }} # ✅ Use o seu token novo aqui
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
